# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Dev Deploy

on:
  push:
    branches: [ "staging" ]
  pull_request:
    branches: [ "staging" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # - name: Set up Go
    #   uses: actions/setup-go@v3
    #   with:
    #     go-version: 1.20

    # - name: Build
    #   run: go build -o main

    # - name: Test
    #   run: go test -v ./...
    - name: Deploying
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSHKEY }}
        script: |
          cd /var/www/word-combinator-dev
          git checkout staging
          git pull origin staging
          sudo docker compose up words-combinator -d --build
          sudo docker compose ps
          sudo docker compose exec -i words-combinator sh "./script.sh"
          sudo docker image prune -a -f
          sudo docker system prune -f
          # sudo systemctl daemon-reload
          # sudo systemctl restart word-combinator-dev
