# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Prod Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # - name: Set up Go
    #   uses: actions/setup-go@v3
    #   with:
    #     go-version: 1.20

    # - name: Build
    #   run: go build -o main

    # - name: Test
    #   run: go test -v ./...
    - name: Deploying
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSHKEY }}
        script: |
          cd /var/www/word-combinator
          sudo git pull origin main
          sudo make mgup
          sudo go build -o app 
          sudo pm2 restart words-combinator
          # sudo systemctl restart word-combinator
